### ISSUE TITLE
Local per project slushes 

### ISSUE THREAD

**Issue by DarrylD** [slushjs/slush#30] opened 2015-02-20 20:59 UTC
I saw this on the readme

`All slush-* packages should be installed globally (for now) to be found by the slush executable.`

What are the thoughts on installing local? 

Currently exploring the possibilities of having smaller custom generators based on a particular project (some already in development) conventions. In these situations, install the generators globally wouldn't be ideal for our case.

**Comment by heikki** [comment] 2015-02-20 21:06
Duplicate of https://github.com/slushjs/slush/issues/5

**Comment by joakimbeng** [comment] 2015-02-23 07:48
Yes, see #5 for this.

**Closed by joakimbeng** 2015-02-23 07:48 UTC
